inputs:
  slack_func:
    description: 'Slack message format function to use'
    required:  true
  release_tag:
    description: 'Release tag to build'
    required: true
  url_prefix:
    description: 'Prefix to add to package URLs'
    required: true
  env:
    description: 'Packages target s3 environment'
    required: true
  packages_json:
    description: 'JSON structure of uploaded packages by distribution and architecture'
    required: true
  message:
    description: 'Message to send in case of failure'
    required: false
  SLACK_WEB_HOOK_URL:
    description: 'Slack web hook URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack notification
      if: inputs.slack_func == 'slack_format_success_message'
      shell: bash
      run: |
        workflow_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        footer="Repository: ${{ github.repository }} | Commit: \`${{ github.sha }}\` | View: <$workflow_url|workflow run>"

        . ${{ github.action_path }}/../common/slack.sh

        cat <<'JSON' | slack_format_success_message \
        "${{ inputs.release_tag }}" "${{ inputs.url_prefix }}" "$footer" \
        | curl -s --fail-with-body -d@- "${{ inputs.SLACK_WEB_HOOK_URL }}"
        ${{ inputs.packages_json }}
        JSON

    - name: Send Failure Slack notification
      if: inputs.slack_func == 'slack_format_failure_message'
      shell: bash
      run: |
        workflow_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        footer="Repository: ${{ github.repository }} | Commit: \`${{ github.sha }}\`"

        msg = ${{ inputs.message }}
        if [ -z "$msg" ]; then
          echo "Error: message is required"
          exit 1
        fi

        . ${{ github.action_path }}/../common/slack.sh

        slack_format_failure_message "$msg for Redis: ${{ inputs.release_tag || 'unknown'}} (${{ inputs.env }})" "$workflow_url" "$footer" \
        | curl -s --fail-with-body -d@- "${{ inputs.SLACK_WEB_HOOK_URL }}"