name: "Build source package"

inputs:
  dist:
    description: "Distribution to build for"
    required: true
  arch:
    description: "Architecture to build for"
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Install dependencies
    shell: bash
    run: |
      sudo apt-get update && \
      sudo apt-get install \
      debhelper dput tcl-tls libsystemd-dev pkgconf cmake clang libssl-dev
  - name: Determine version
    shell: bash
    run: |
      # Version format:
      # https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
      VERSION=$(head -1 debian/changelog | awk '{print $2}' | sed 's/(\([0-9]\+:\)\?\(.*\)-[^-]\+)$/\2/g')
      echo "Determined version $VERSION"
      echo "VERSION=${VERSION}" >> $GITHUB_ENV
  - name: Get source tarball
    shell: bash
    run: |
      curl --silent -L "https://github.com/redis/redis/archive/${VERSION}.tar.gz" -o redis_${VERSION}.orig.tar.gz
  - name: Build source package
    shell: bash
    run: |
      mkdir -p redis-${VERSION}
      tar --extract --gunzip --file redis_${VERSION}.orig.tar.gz --strip-components=1 -C redis-${VERSION}
      sed -i 's/INSTALL_BIN=\$(PREFIX)\/bin/INSTALL_BIN=\$(DESTDIR)\$(PREFIX)\/bin/' redis-${VERSION}/src/Makefile
      cp -pr debian redis-${VERSION}
      sed -i "s/@RELEASE@/${{ inputs.dist }}/g" redis-${VERSION}/debian/changelog
      ( cd redis-${VERSION} && dpkg-buildpackage -S )
  - name: Upload source package artifact
    uses: actions/upload-artifact@v4
    with:
      name: source-${{ inputs.dist }}-${{ inputs.arch }}
      path: |
        redis_*.tar.xz
        redis_*.dsc
        redis_*.orig.tar.gz
