name: "Build source package"

inputs:
  dist:
    description: "Distribution to build for"
    required: true
  release_tag:
    description: "Release tag to build for (value 'unstable' is supported)"
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Install dependencies
    shell: bash
    run: |
      sudo apt-get update && \
      sudo apt-get install \
      debhelper dput tcl-tls libsystemd-dev pkgconf cmake clang libssl-dev
  - name: Determine version
    id: determine-version
    shell: bash
    run: |
      if [ "${{ inputs.release_tag }}" == "unstable" ]; then
        VERSION="unstable"
        URL="https://github.com/redis/redis/archive/refs/heads/${VERSION}.tar.gz"
      else
        # Version format:
        # https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
        VERSION=$(head -1 debian/changelog | awk '{print $2}' | sed 's/(\([0-9]\+:\)\?\(.*\)-[^-]\+)$/\2/g')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        URL="https://github.com/redis/redis/archive/${VERSION}.tar.gz"
      fi
      echo "Determined version $VERSION"
      echo "URL=${URL}"
      echo "URL=${URL}" >> $GITHUB_OUTPUT
  - name: Get source tarball
    shell: bash
    run: |
      curl --silent -L ${{ steps.determine-version.outputs.URL }} -o redis_${VERSION}.orig.tar.gz
  - name: Build source package
    shell: bash
    run: |
      mkdir -p redis-${VERSION}
      tar --extract --gunzip --file redis_${VERSION}.orig.tar.gz --strip-components=1 -C redis-${VERSION}
      sed -i 's/INSTALL_BIN=\$(PREFIX)\/bin/INSTALL_BIN=\$(DESTDIR)\$(PREFIX)\/bin/' redis-${VERSION}/src/Makefile

      if [ "${{ inputs.release_tag }}" == "unstable" ]; then
        echo "===== Updating all Redis module versions to 'master' ====="
        find redis-${VERSION}/modules -name "Makefile" -type f | while read -r makefile; do
          echo "Processing $makefile"
          echo "  Before change:"
          grep "MODULE_VERSION" "$makefile" || echo "  No MODULE_VERSION found"

          # Update the MODULE_VERSION to 'master'
          sed -i 's/MODULE_VERSION = .*/MODULE_VERSION = master/g' "$makefile"

          echo "  After change:"
          grep "MODULE_VERSION" "$makefile" || echo "  No MODULE_VERSION found after update"
          echo "-----------------------------------"
        done
        echo "===== Module version updates completed ====="
      fi

      cp -pr debian redis-${VERSION}
      sed -i "s/@RELEASE@/${{ inputs.dist }}/g" redis-${VERSION}/debian/changelog
      ( cd redis-${VERSION} && dpkg-buildpackage -S )
  - name: Upload source package artifact
    uses: actions/upload-artifact@v4
    with:
      name: source-${{ inputs.dist }}
      path: |
        redis_*.tar.xz
        redis_*.dsc
        redis_*.orig.tar.gz
