.TH REDIS-CHECK-RDB 1 "December 13, 2018"
.SH NAME
redis-check-rdb \- Check integrity of Redis dumped database file
.SH SYNOPSIS
.B redis-check-rdb
filename
.SH DESCRIPTION
Redis is a key-value database. It is similar to memcached but the dataset is
not volatile and other datatypes (such as lists and sets) are natively
supported.
.PP
This utility checks the integrity of a dumped database file.
.SH AUTHOR
\fBredis-check-rdb\fP was written by Salvatore Sanfilippo.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
