#!/bin/sh

set -eu

USER="redis"

Setup_dir () {
	DIR="${1}"
	MODE="${2}"
	GROUP="${3}"

	mkdir -p ${DIR}

	if ! dpkg-statoverride --list ${DIR} >/dev/null 2>&1
	then
		chown ${USER}:${GROUP} ${DIR}
		chmod ${MODE} ${DIR}
	fi
}

if [ "$1" = "configure" ]
then
	adduser \
		--system \
		--home /var/lib/redis \
		--quiet \
		--group \
		${USER} || true

	Setup_dir /var/log/redis 2750 adm
	Setup_dir /var/lib/redis 750 ${USER}
	Setup_dir /etc/redis 2770 ${USER}
fi

#DEBHELPER#

exit 0
