
name: Build and Test All Distros

on:
  workflow_call:
    inputs:
      BUILD_DISTS:
        type: string
      BUILD_ARCHS:
        type: string
      BUILD_EXCLUDE:
        type: string
      SMOKE_TEST_IMAGES:
        type: string


jobs:
  build-source-package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dist: ${{ fromJSON(inputs.BUILD_DISTS) }}
    steps:
    - uses: ./.github/actions/build-source-package
      with:
        dist: ${{ matrix.dist }}

  build-binary-package:
    runs-on: ${{ contains(matrix.arch, 'arm') && 'ubuntu24-arm64-2-8' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        dist: ${{ fromJSON(inputs.BUILD_DISTS) }}
        arch: ${{ fromJSON(inputs.BUILD_ARCHS) }}
        exclude: ${{ fromJSON(inputs.BUILD_EXCLUDE) }}
    needs: build-source-package
    steps:
    - uses: ./.github/actions/build-binary-package
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        run_id: ${{ github.run_id }}

  smoke-test-packages:
    runs-on: ubuntu-latest
    needs: build-binary-package
    env:
      ARCH: amd64
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(inputs.SMOKE_TEST_IMAGES) }}
    container: ${{ matrix.image }}
    steps:
    - uses: ./.github/actions/run-smoke-tests
      with:
        image: ${{ matrix.image }}
        run_id: ${{ github.run_id }}