name: Nightly Unstable Build and Package

on:
  schedule:
    - cron: '0 1 * * *'  # Run at 1:00 AM UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  trigger-unstable-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger apt.yml workflow on unstable branch
        run: |
          gh workflow run apt.yml --ref unstable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
