on:
  # push:
  #   branches:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build'
        required: true
      workflow_uuid:
        description: 'Optional UUID to identify this workflow run'
        required: false
      run_id:
        description: 'Run ID to download artifacts from'
        required: true


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # to configure-aws-credentials with a role
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload staging packages
        uses: ./.github/actions/upload-packages
        with:
          run_id: ${{ github.event.inputs.run_id }}
          release_type: internal
          APT_SIGNING_KEY: ${{ secrets.APT_SIGNING_KEY }}
          APT_S3_BUCKET: ${{ secrets.APT_S3_BUCKET_STAGING }}
          APT_S3_REGION: ${{ secrets.APT_S3_REGION }}
          APT_S3_IAM_ARN: ${{ secrets.APT_S3_IAM_ARN_STAGING }}