on:
  # push:
  #   branches:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build'
        required: true
      workflow_uuid:
        description: 'Optional UUID to identify this workflow run'
        required: false

# UUID is used to help automation to identify workflow run in the list of workflow runs.
run-name: "Release Build and Test${{ github.event.inputs.workflow_uuid && format(': {0}', github.event.inputs.workflow_uuid) || '' }}"

jobs:
  prepare-release:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Redis Release Archive
        uses: redis-developer/redis-oss-release-automation/.github/actions/validate-redis-release-archive@main
        with:
          release_tag: ${{ github.event.inputs.release_tag }}

      - name: Ensure Release Branch
        id: ensure-branch
        uses: redis-developer/redis-oss-release-automation/.github/actions/ensure-release-branch@main
        with:
          release_tag: ${{ github.event.inputs.release_tag }}
          allow_modify: true
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump Debian Changelog
        id: bump-changelog
        uses: ./.github/actions/bump-debian-changelog
        with:
          release_tag: ${{ github.event.inputs.release_tag }}
          release_version_branch: ${{ steps.ensure-branch.outputs.release_version_branch }}

  build-n-test:
    needs: prepare-release
    uses: ./.github/workflows/build-n-test-all-distros.yml
    with:
      BUILD_DISTS: ${{ vars.BUILD_DISTS }}
      BUILD_ARCHS: ${{ vars.BUILD_ARCHS }}
      BUILD_EXCLUDE: ${{ vars.BUILD_EXCLUDE }}
      SMOKE_TEST_IMAGES: ${{ vars.SMOKE_TEST_IMAGES }}
      release_tag: ${{ inputs.release_tag }}

  create-release-handle:
    needs: build-n-test
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Handle
        shell: bash
        run: |
          cat <<RELEASE_HANDLE >release_handle.json
          {
            "release_tag": "${{ github.event.inputs.release_tag }}",
            "run_id": ${{ github.run_id }},
            "workflow_uuid": "${{ github.event.inputs.workflow_uuid }}"
          }
          RELEASE_HANDLE

      - name: Upload release handle artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_handle
          path: release_handle.json
          retention-days: 400
