on:
  push:
    branches:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build'
        required: true
      workflow_uuid:
        description: 'Optional UUID to identify this workflow run'
        required: false


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.APT_S3_IAM_ARN_STAGING }}
          aws-region: us-east-1

      - name: Test S3 bucket access
        shell: bash
        run: |
          aws s3 ls s3://redis-test-package-repository/

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.APT_S3_IAM_ARN }}
          aws-region: us-east-1

      - name: Test S3 bucket access
        shell: bash
        run: |
          aws s3 ls s3://redislabs-dev-apt-repository/