on:
  # push:
  #   branches:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build'
        required: true
      workflow_uuid:
        description: 'Optional UUID to identify this workflow run'
        required: false

# UUID is used to help automation to identify workflow run in the list of workflow runs.
run-name: "Release Build and Test${{ github.event.inputs.workflow_uuid && format(': {0}', github.event.inputs.workflow_uuid) || '' }}"

jobs:
  build-n-test:
    uses: ./.github/workflows/build-n-test-all-distros.yml
    with:
      BUILD_DISTS: ${{ vars.BUILD_DISTS }}
      BUILD_ARCHS: ${{ vars.BUILD_ARCHS }}
      BUILD_EXCLUDE: ${{ vars.BUILD_EXCLUDE }}
      SMOKE_TEST_IMAGES: ${{ vars.SMOKE_TEST_IMAGES }}